// mypage.js
// 2023-03-01 by jpf


exports.pessoaPage = function(pessoa,data){
    var flag_BI = false
    var flag_desc = false
    if(pessoa.BI)
        flag_BI=true
    if(pessoa.descrição)
        flag_desc=true
   
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>${pessoa.nome}</title>
        <link rel="stylesheet" href="w3.css"/> 
    </head>
    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-teal">
                <h1>${pessoa.nome}</h1>
            </header>
    
        <div class="w3-container">
            <p><b>Idade:</b> ${pessoa.idade}</p>
            <p><b>Sexo:</b> ${pessoa.sexo}</p>`
    if(flag_BI){

        pagHTML+=`
            <p><b>BI:</b> ${pessoa.BI}</p>
        `
    }
    else{
        pagHTML+=`
            <p><b>CC:</b> ${pessoa.CC}</p>
        `
    }
    if(flag_desc){
        pagHTML+=`
            <p><b>Descrição:</b> ${pessoa.descrição}</p>
        `
    }
    pagHTML+=`
            <p><b>Morada:</b> ${pessoa.morada.cidade} (${pessoa.morada.distrito})</p>
            <p><b>Profissão:</b> ${pessoa.profissao}</p>       
            <p><b>Partido Político:</b> ${pessoa.partido_politico.party_name} (${pessoa.partido_politico.party_abbr})</p>
            <p><b>Religião</b> ${pessoa.religiao}</p>
            <p><b>Desportos:</b></p>
            <ul>        
            `
    for(let i=0; i<pessoa.desportos.length;i++){
        pagHTML+=`
                <li>${pessoa.desportos[i]}</li>
                `
    }
    pagHTML+=`
            </ul>`
    
    pagHTML+=`            
            <p><b>Animais Favoritos:</b></p>
            <ul>        
    `
    for(let i=0; i<pessoa.animais.length;i++){
    pagHTML+=`
                <li>${pessoa.animais[i]}</li>
            `
    }
    pagHTML+=`
            </ul>`
    pagHTML+=`            
            <p><b>Figura Pública:</b></p>
            <ul>        
    `
    for(let i=0; i<pessoa.figura_publica_pt.length;i++){
    pagHTML+=`
                <li>${pessoa.figura_publica_pt[i]}</li>
            `
    }
    pagHTML+=`
            </ul>`
    pagHTML+=`            
            <p><b>Destinos Favoritos:</b></p>
            <ul>        
    `
    for(let i=0; i<pessoa.animais.length;i++){
    pagHTML+=`
                <li>${pessoa.destinos_favoritos[i]}</li>
            `
    }
    pagHTML+=`
            </ul>`
    pagHTML+=`
            <p><b>Atributos</b></p>
            <table class="w3-table-all">
                <tr>
                    <th>Fumador</th>
                    <th>Gosta de cinema</th>
                    <th>Gosta de Viajar</th>
                    <th>Acorda cedo</th>
                    <th>Gosta de Ler</th>
                    <th>Gosta de música</th>
                    <th>Gosta de Comer</th>
                    <th>Gosta de Animais de estimação</th>
                    <th>Gosta de Dançar</th>
                </tr>
                <tr>
                    <td>${pessoa.atributos.fumador}</td>
                    <td>${pessoa.atributos.gosta_cinema}</td>
                    <td>${pessoa.atributos.gosta_viajar}</td>
                    <td>${pessoa.atributos.acordar_cedo}</td>
                    <td>${pessoa.atributos.gosta_ler}</td>
                    <td>${pessoa.atributos.gosta_musica}</td>
                    <td>${pessoa.atributos.gosta_comer}</td>
                    <td>${pessoa.atributos.gosta_animais_estimacao}</td>
                    <td>${pessoa.atributos.gosta_dancar}</td>
                </tr>
            </table>
            <p><b>Comida Favorita:</b> ${pessoa.atributos.comida_favorita}</p>
            <p><b>Marca do Carro:</b> ${pessoa.marca_carro}</p>
            <div class="w3-center">
                <button class="w3-button w3-round-xlarge w3-large w3-hover-grey w3-teal"><a href="http://localhost:7777/">Home</a></button>
            </div
            `
    pagHTML+= `
        </div>
        <br/>
        <footer class="w3-container w3-teal">
            <h5>Generated by pessoas-server:${data}</h5>
        </footer>

        </div> 
    </body>
</html>
    `
return pagHTML
}


exports.getMainPage = function(lista,data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/> 
    </head>
    <body>
        <div class="w3-card-4">

            <header class="w3-container w3-teal">
                <h1>Lista de Pessoas na Base de Dados {${lista.length}}</h1>
            </header>
    
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                  <th>ID</th>
                  <th>Nome</th>
                  <th>Idade</th>
                  <th>Sexo</th>
                  <th>Cidade</th>
                </tr>`
    
    for(let i=0; i<lista.length; i++){
        pagHTML += `
                <tr>
                    <td>${lista[i].id}</td>
                    <td>
                        <a href="http://localhost:7777/pessoas/${lista[i].id}">
                        ${lista[i].nome}
                        </a>
                    </td>
                    <td>${lista[i].idade}</td>
                    <td>${lista[i].sexo}</td>
                    <td>${lista[i].morada.cidade}</td>
                </tr>        
        `
    }            
    
    pagHTML+= `           
            </table>
        </div>

        <footer class="w3-container w3-teal">
            <h5>Generated by pessoas-server:${data}</h5>
        </footer>

        </div> 
    </body>
</html>
    `
return pagHTML
}